### Register New User

POST http://localhost:8080/coordinator/signUp
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "testPassword",
  "name": "Test Name"
}

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "testPassword"
}
